import slugsData from './slugs.json'
import type { Unit } from './types'

/**
 * DRAFT stand-in for `corpus.db`'s ingredient table (`IngredientsRow` in `types.ts`). Generated by
 * `scripts/gen_slugs.py` from `ingest/taxonomy/ingredients.yaml` — run that script, then
 * `npx prettier --write src/corpus/slugs.json`, after the taxonomy changes. Search-by-synonym for
 * the kitchen list ("what I have") needs slug + name + synonyms + aisle; the grocery list needs
 * the purchase fields (S7c). This stays a small export rather than the app depending on `ingest`.
 */
export interface IngredientSlug {
  slug: string
  name: string
  synonyms: string[]
  aisle: string
  /** Purchase fields (S7c; `ingest/taxonomy/ingredients.yaml` `shop_unit` / `yield` /
   * `buy_as`), set on the ~300 most-used slugs only. */
  shopUnit?: ShopUnit
  yield?: { qty: number; unit: Unit }
  buyAs?: string
}

/** What a shopper buys an ingredient in (taxonomy `shop_unit`, SHOP_UNITS in taxonomy.py). */
export type ShopUnit = 'piece' | 'bunch' | 'head' | 'g' | 'ml' | 'can' | 'bottle' | 'jar' | 'pack'

export interface Purchase {
  shopUnit: ShopUnit
  /** How much of this slug one shop unit (of `buyAs`, when set) gives. */
  yield: { qty: number; unit: Unit } | null
  /** The slug actually bought (lemon_juice -> lemon); null when it is bought as itself. */
  buyAs: string | null
}

export const INGREDIENT_SLUGS: IngredientSlug[] = slugsData as IngredientSlug[]

const BY_SLUG = new Map<string, IngredientSlug>(INGREDIENT_SLUGS.map((item) => [item.slug, item]))

export function getIngredientSlug(slug: string): IngredientSlug | undefined {
  return BY_SLUG.get(slug)
}

/** Display name for a slug, falling back to a readable version of the slug itself. */
export function ingredientName(slug: string): string {
  return BY_SLUG.get(slug)?.name ?? slug.replace(/_/g, ' ')
}

export function ingredientAisle(slug: string): string {
  return BY_SLUG.get(slug)?.aisle ?? 'other'
}

/** The slug's purchase fields, or null when the taxonomy has none for it. */
export function ingredientPurchase(slug: string): Purchase | null {
  const item = BY_SLUG.get(slug)
  if (!item?.shopUnit) return null
  return { shopUnit: item.shopUnit, yield: item.yield ?? null, buyAs: item.buyAs ?? null }
}

function normalize(value: string): string {
  return value.toLowerCase().trim()
}

/**
 * Type-ahead search over name and every synonym, so "cilantro", "coriander" or "dhania" each
 * find the same ingredient (docs/PRODUCT.md, "Kitchen list"). Case-insensitive substring match;
 * results are sorted by name and capped at `limit`.
 */
export function searchIngredientSlugs(query: string, limit = 20): IngredientSlug[] {
  const q = normalize(query)
  if (!q) return []
  const matches = INGREDIENT_SLUGS.filter(
    (item) =>
      normalize(item.name).includes(q) || item.synonyms.some((s) => normalize(s).includes(q)),
  )
  return matches.sort((a, b) => a.name.localeCompare(b.name)).slice(0, limit)
}
