import slugsData from './slugs.json'

/**
 * DRAFT stand-in for `corpus.db`'s ingredient table (see `draft.ts`). Generated by
 * `scripts/gen_slugs.py` from `ingest/taxonomy/ingredients.yaml` — run that script again to
 * refresh this file after the taxonomy changes. Search-by-synonym for the kitchen list ("what
 * I have") needs slug + name + synonyms + aisle; nothing else does yet, so this stays a small
 * export rather than the app depending on `ingest`.
 */
export interface IngredientSlug {
  slug: string
  name: string
  synonyms: string[]
  aisle: string
}

export const INGREDIENT_SLUGS: IngredientSlug[] = slugsData as IngredientSlug[]

const BY_SLUG = new Map<string, IngredientSlug>(INGREDIENT_SLUGS.map((item) => [item.slug, item]))

export function getIngredientSlug(slug: string): IngredientSlug | undefined {
  return BY_SLUG.get(slug)
}

/** Display name for a slug, falling back to a readable version of the slug itself. */
export function ingredientName(slug: string): string {
  return BY_SLUG.get(slug)?.name ?? slug.replace(/_/g, ' ')
}

export function ingredientAisle(slug: string): string {
  return BY_SLUG.get(slug)?.aisle ?? 'other'
}

function normalize(value: string): string {
  return value.toLowerCase().trim()
}

/**
 * Type-ahead search over name and every synonym, so "cilantro", "coriander" or "dhania" each
 * find the same ingredient (docs/PRODUCT.md, "Kitchen list"). Case-insensitive substring match;
 * results are sorted by name and capped at `limit`.
 */
export function searchIngredientSlugs(query: string, limit = 20): IngredientSlug[] {
  const q = normalize(query)
  if (!q) return []
  const matches = INGREDIENT_SLUGS.filter(
    (item) =>
      normalize(item.name).includes(q) || item.synonyms.some((s) => normalize(s).includes(q)),
  )
  return matches.sort((a, b) => a.name.localeCompare(b.name)).slice(0, limit)
}
