// GENERATED by ingest/build/gen_types.py from schema/corpus.sql. Do not edit by hand:
// `ingest` owns the corpus schema (ruling R4); change schema/corpus.sql and regenerate.

/** corpus_meta.schema_version this app was built against. */
export const CORPUS_SCHEMA_VERSION = 1

export const AISLE_VALUES = [
  'produce',
  'dairy',
  'meat',
  'seafood',
  'bakery',
  'pantry',
  'spices',
  'international',
  'frozen',
  'beverages',
  'other',
] as const
export type Aisle = (typeof AISLE_VALUES)[number]

export const COURSE_VALUES = [
  'main',
  'side',
  'dessert',
  'breakfast',
  'snack',
  'drink',
  'sauce_condiment',
  'baking',
] as const
export type Course = (typeof COURSE_VALUES)[number]

export const CUISINE_VALUES = [
  'indian',
  'chinese',
  'japanese',
  'korean',
  'thai',
  'vietnamese',
  'filipino',
  'indonesian_malaysian',
  'middle_eastern',
  'persian',
  'turkish',
  'greek',
  'italian',
  'french',
  'spanish',
  'mediterranean',
  'mexican',
  'latin_american',
  'caribbean',
  'american',
  'southern_us',
  'british_irish',
  'german_central_eu',
  'north_african',
  'east_west_african',
  'fusion_other',
] as const
export type Cuisine = (typeof CUISINE_VALUES)[number]

export const CUISINE_SOURCE_VALUES = ['source_label', 'classifier'] as const
export type CuisineSource = (typeof CUISINE_SOURCE_VALUES)[number]

export const DIET_PRESET_VALUES = ['vegetarian', 'no_red_meat', 'vegetarian_strict'] as const
export type DietPreset = (typeof DIET_PRESET_VALUES)[number]

export const DIET_STATUS_VALUES = ['ok', 'adaptable', 'no', 'unknown'] as const
export type DietStatus = (typeof DIET_STATUS_VALUES)[number]

export const EQUIPMENT_VALUES = [
  'oven',
  'stovetop',
  'microwave',
  'grill',
  'broiler',
  'air_fryer',
  'slow_cooker',
  'pressure_cooker',
  'rice_cooker',
  'deep_fryer',
  'smoker',
  'toaster',
  'toaster_oven',
  'sous_vide',
  'waffle_iron',
  'bread_machine',
  'dehydrator',
  'campfire',
  'steamer',
  'food_processor',
  'blender',
  'immersion_blender',
  'mortar_pestle',
  'wok',
  'stand_mixer',
  'hand_mixer',
  'dutch_oven',
  'cast_iron',
  'sheet_pan',
  'spice_grinder',
  'ice_cream_maker',
] as const
export type Equipment = (typeof EQUIPMENT_VALUES)[number]

export const INGREDIENT_CATEGORY_VALUES = [
  'sauce_condiment',
  'vinegar_acid',
  'dairy',
  'nondairy',
  'egg',
  'flour_thickener',
  'leavener',
  'sweetener',
  'chocolate_cocoa',
  'fat_oil',
  'herb',
  'spice',
  'spice_blend',
  'salt',
  'aromatic',
  'chile',
  'alcohol',
  'stock',
  'protein',
  'pantry',
  'nut_seed',
  'basic',
  'vegetable',
  'fruit',
  'grain',
  'cereal',
  'pasta_noodle',
  'legume',
  'bakery',
  'snack',
  'dessert_sweet',
  'beverage',
  'prepared',
  'nonfood',
] as const
export type IngredientCategory = (typeof INGREDIENT_CATEGORY_VALUES)[number]

export const INGREDIENT_FLAG_VALUES = [
  'red_meat',
  'poultry',
  'fish',
  'shellfish',
  'animal_derived',
  'explicit_meat',
  'dairy',
  'egg',
  'gluten',
  'nuts',
  'alcohol',
] as const
export type IngredientFlag = (typeof INGREDIENT_FLAG_VALUES)[number]

export const SUB_CONTEXT_VALUES = [
  'baking',
  'sauce',
  'marinade',
  'dressing',
  'stir_fry',
  'braise',
  'soup',
  'frying',
  'garnish',
  'dessert',
  'beverage',
  'any',
] as const
export type SubContext = (typeof SUB_CONTEXT_VALUES)[number]

export const SWAP_VIA_VALUES = ['alternative', 'substitution', 'omit'] as const
export type SwapVia = (typeof SWAP_VIA_VALUES)[number]

export const TIME_SOURCE_VALUES = ['source', 'source_partial', 'estimated'] as const
export type TimeSource = (typeof TIME_SOURCE_VALUES)[number]

export const UNIT_VALUES = [
  'g',
  'kg',
  'mg',
  'ml',
  'l',
  'tsp',
  'tbsp',
  'cup',
  'fl_oz',
  'oz',
  'lb',
  'pint',
  'quart',
  'gallon',
  'pinch',
  'dash',
  'drop',
  'splash',
  'drizzle',
  'clove',
  'piece',
  'slice',
  'can',
  'jar',
  'bottle',
  'package',
  'bunch',
  'sprig',
  'stalk',
  'head',
  'stick',
  'sheet',
  'leaf',
  'handful',
  'inch',
  'ear',
  'cube',
  'loaf',
  'knob',
  'scoop',
  'square',
] as const
export type Unit = (typeof UNIT_VALUES)[number]

export const UNIT_DIMENSION_VALUES = ['volume', 'mass', 'count'] as const
export type UnitDimension = (typeof UNIT_DIMENSION_VALUES)[number]

/** A row of `corpus_meta`. */
export interface CorpusMetaRow {
  key: string
  value: string
}

/** A row of `recipes`. */
export interface RecipesRow {
  /** dense build-local id; the posting lists use it. Not stable across builds. */
  id: number
  /** the raw id "<source>:<native id>", stable across builds: user.db refers to recipes by this */
  key: string
  /** a key of ingest/sources.md */
  source: string
  source_url: string | null
  title: string
  /** head count parsed from yield_text; NULL when the yield is not a head count */
  servings: number | null
  /** the source's own yield string, as given */
  yield_text: string | null
  /** total minutes; NULL when unknown */
  total_min: number | null
  /** hands-on minutes; NULL when unknown */
  active_min: number | null
  time_source: TimeSource | null
  /** total_min <= 30; NULL when total_min is unknown */
  weeknight: 0 | 1 | null
  cuisine: Cuisine | null
  /** 1.0 for a mapped source label, else the classifier's posterior; NULL with cuisine */
  cuisine_confidence: number | null
  cuisine_source: CuisineSource | null
  course: Course
  /** a single heated vessel (literal, R9); "one pot meals" is one_pot AND course = 'main' */
  one_pot: 0 | 1 | null
  one_pan: 0 | 1 | null
  sheet_pan_meal: 0 | 1 | null
  /** uses both the hob and the oven */
  stove_and_oven: 0 | 1 | null
  /** no heat source at all */
  no_cook: 0 | 1
  image_url: string | null
  /** the source's own rating, 5-point scale; NULL when unrated */
  rating: number | null
  rating_count: number | null
  /** 0..1, ingest/build/curate.py quality_score */
  quality: number
  /** ingredient lines */
  line_count: number
  /** ingredient lines with no slug */
  unresolved_count: number
  /** distinct non-staple, non-optional slugs: the denominator of "how much can I cover" */
  core_slug_count: number
  /** nutrition per serving, estimated from USDA FoodData Central; NULL until that slice lands */
  kcal: number | null
  protein_g: number | null
  fat_g: number | null
  carbs_g: number | null
  fiber_g: number | null
  sugar_g: number | null
  sodium_mg: number | null
}

/** A row of `recipe_ingredients`. */
export interface RecipeIngredientsRow {
  recipe_id: number
  /** item order within the recipe, from 0 */
  position: number
  /** the raw ingredient line this item came from, from 0 */
  line: number
  /** first number; the low end of a range */
  qty: number | null
  /** the high end of a range, else NULL */
  qty_max: number | null
  unit: Unit | null
  /** canonical ingredient; NULL when the line could not be resolved */
  slug: string | null
  /** the ingredient line as the source wrote it */
  raw: string
  /** "finely chopped", "drained" */
  prep: string | null
  optional: 0 | 1
  note: string | null
  /** container size: "1 (14 oz) can" gives pkg_qty 14, pkg_unit 'oz' */
  pkg_qty: number | null
  pkg_unit: Unit | null
}

/** A row of `recipe_slugs`. */
export interface RecipeSlugsRow {
  slug: string
  recipe_id: number
  /** used non-optionally and not a staple; only core slugs count toward coverage */
  core: 0 | 1
}

/** A row of `steps`. */
export interface StepsRow {
  recipe_id: number
  /** from 0 */
  position: number
  text: string
}

/** A row of `recipe_equipment`. */
export interface RecipeEquipmentRow {
  recipe_id: number
  equipment: Equipment
}

/** A row of `recipe_equipment_alternatives`. */
export interface RecipeEquipmentAlternativesRow {
  recipe_id: number
  /** group number within the recipe, from 0 */
  grp: number
  equipment: Equipment
}

/** A row of `recipe_diet`. */
export interface RecipeDietRow {
  recipe_id: number
  preset: DietPreset
  status: DietStatus
  /** JSON-encoded `DietSwap[]`. What makes an adaptable recipe work; [] unless status = 'adaptable' */
  swaps: string
}

/** A row of `ingredients`. */
export interface IngredientsRow {
  slug: string
  /** display name */
  name: string
  /** the broader slug a variety falls back to (roma_tomato -> tomatoes) */
  parent: string | null
  category: IngredientCategory
  aisle: Aisle
  /** JSON-encoded `IngredientFlag[]`. The diet flags that are true */
  flags: string
  /** for volume <-> mass conversion */
  density_g_per_ml: number | null
  /** grams in one piece */
  each_g: number | null
  /** assumed on hand; ignored by coverage */
  is_staple: 0 | 1
  /** search hint for the USDA FoodData Central match */
  usda_hint: string | null
  /** recipes in this corpus.db that use the slug (any line, optional included) */
  recipe_count: number
}

/** A row of `ingredient_synonyms`. */
export interface IngredientSynonymsRow {
  /** another name, as written in the taxonomy (UK/US/Indian spellings, generic brand names) */
  synonym: string
  slug: string
}

/** A row of `substitutions`. */
export interface SubstitutionsRow {
  id: string
  target: string
  /** the target unit absolute amounts are given for, else NULL */
  per_unit: string | null
  /** 3 hard to tell apart, 2 good, 1 in a pinch */
  quality: number
  /** JSON-encoded `SubContext[]`. */
  contexts: string
  /** JSON-encoded `string[]`. */
  cuisines: string
  /** JSON-encoded `IngredientFlag[]`. The diet flags of the substitute, computed from its components */
  flags: string
  note: string | null
  flavor_effect: string
}

/** A row of `substitution_components`. */
export interface SubstitutionComponentsRow {
  substitution_id: string
  /** from 0 */
  position: number
  slug: string
  amount: number
  /** 'x' (a multiple of the target quantity) or a unit per substitutions.per_unit */
  unit: string
}

/** A row of `season`. */
export interface SeasonRow {
  slug: string
  /** JSON-encoded `number[]`. 1 = January .. 12 = December */
  months: string
  /** bit (month - 1) set for each peak month */
  month_mask: number
}

/** A row of `units`. */
export interface UnitsRow {
  unit: Unit
  dimension: UnitDimension
  /** ml per unit for volume, g per unit for mass; NULL for count units */
  to_base: number | null
}

/** A row of `build_sources`. */
export interface BuildSourcesRow {
  source: string
  /** lines in the raw file when the build first opened it */
  lines_total: number
  /** lines to select; NULL for all */
  quota: number | null
  /** resume point: the first raw line not yet committed */
  next_line: number
  /** lines read */
  selected: number
  /** recipes written */
  written: number
  done: 0 | 1
}

/** A row of `build_drops`. */
export interface BuildDropsRow {
  source: string
  /** one of ingest/build/curate.py DROP_REASONS */
  reason: string
  count: number
  /** the first dropped id (or line number) for this reason */
  example: string | null
}
